export { default as Slider1 } from "./Slider.png";
export { default as FooterImage } from "./Footer.png";
export { default as NonoImage } from "./nono new 1.png";
export { default as GirlRunningImage } from "./newfbdfhdf 1.png";
export { default as HTGSBGImage } from "./HowToGetStartedBackGroundImage.png";
export { default as AnimalImage } from "./FF 1.png";
export { default as RegistrationGuideBGImage } from "./RegistrationGuideBG.png";
export { default as bronze } from "./Bronze.png";
export { default as sliver } from "./Sliver.png";
export { default as gold } from "./Gold.png";
export { default as DCDDPageBackGroundImage } from "./bgimage1.png";
export { default as ThreeCharacterImage } from "./ThreeCharacter.png";
export { default as FamilyWithPhoneImage } from "./FamilyWithPhone.png";
export * from "./logo";
export * from "./social-media";
export * from "./educare-skill";
export * from "./frames";