export { default as ManagementTeamProfile } from "./Management Team 1.png";
export { default as BGArtistsProfile } from "./BG Artists 1.png";
export { default as ContentWritersProfile } from "./Content Writers 1.png";
export { default as IllustratorsProfile } from "./Illustrators 1.png";
export { default as TwoDAnimatorProfile } from "./2D Animator 1.png";
export { default as ThreeDAnimatorProfile } from "./3D Animator 1.png";
export { default as VideographersProfile } from "./Videographers 1.png";
export { default as MusicDirectorProfile } from "./Music Director 1.png";
export { default as VisualEditorsProfile } from "./Visual Editors 2.png";
export { default as SoftwareDevelopersProfile } from "./Software Developers 1.png";