export { default as Slider1 } from "./1. Chey Chey.jpg";
export { default as Slider2 } from "./2. Educare Kids.jpg";
export { default as Slider3 } from "./3. Primary Level.jpg";
export { default as Slider4 } from "./4. Intermediate level.jpg";
export { default as Slider5 } from "./5. Undergraduite BG.jpg";
export { default as Slider6 } from "./6. Daza.jpg";
export { default as Slider7 } from "./7. Nono.jpg";
export { default as Slider8 } from "./8. Dr. Carrot.jpg";
export { default as Slider9 } from "./9. Four Friends.jpg";
export { default as Slider10 } from "./10. MK Series.jpg";
export { default as Slider11 } from "./11. MK & DT.jpg";