export { default as ManagementTeamProfile } from ".//Management Team.webp";
export { default as BGArtistsProfile } from "./BG Artists.webp";
export { default as ContentWritersProfile } from "./Content Writers.webp";
export { default as IllustratorsProfile } from "./Illustrators .webp";
export { default as TwoDAnimatorProfile } from "./2D Animator.webp";
export { default as ThreeDAnimatorProfile } from "./3D Animator.webp";
export { default as VideographersProfile } from "./Videographers.webp";
export { default as MusicDirectorProfile } from "./Music Director.webp";
export { default as VisualEditorsProfile } from "./Visual Editors.webp";
export { default as SoftwareDevelopersProfile } from "./Software Developers.webp";
